### ISSUE TITLE
Quantized model latency issue. 

### ISSUE THREAD

**Issue by abhijitherekar** [MILVLG/imp#5]
Hi, I am trying to see if I can load a quantized model of this. 

When I load in 4-bit, the model size is smaller but the latency significantly increases. 

Not sure if there needs to be any changes to be done to support quantization. 

Please, let me know. 

I can also help in creating a MR to make the quantized model better. 

Thanks

**Comment by ParadoxZW** [comment]
Hi, thanks for your interesting and response!

Do you mean inference in a quantized format or training using QLoRA which is not supported for Imp yet?

If you mean inference, check if `use_cache` is enabled, and check if the model stop generation after a `</s>` token is generated.

**Comment by abhijitherekar** [comment]
Hi @ParadoxZW , thanks for the reply. 

I am currently using it for inference. 
Here is what I have tried:

model = AutoModelForCausalLM.from_pretrained(
    "MILVLG/imp-v1-3b", 
    torch_dtype=torch.float16, 
    device_map="auto",
    #load_in_4bit=True,
    trust_remote_code=True)
    
    and then while calling forward pass, I set the `use_cache` to true:
        output_ids = model.generate(
        input_ids,
        max_new_tokens=100,
        images=image_tensor,
        use_cache=True)[0]

    When I **load the 4-bit model**, I see the latency to be _1.2_ seconds. 

    But if I **load the normal model** it takes _0.2_ seconds for the same image. 

I will check further on the token generation. 

If you can point to the file where I need to check and try, I can give it a shot in fixing it if you think its a issue. 

Open to help and contribute. 

Thanks

**Comment by abhijitherekar** [comment]
I check for EOS token, I don't see it generated in the output. 

So, I am not sure why a 4-bit quantized model would take more time for inference than the base model.

Are we missing anything ? @ParadoxZW

**Comment by MIL-VLG** [comment]
you can check the output to see whether the quantized model generate much longer outputs than the base model.

**Comment by MIL-VLG** [comment]
@abhijitherekar We have invesitgated the quantization methods recently. According to the existing studies, using int8 or other 4-bit quantization strategies will indeed slow down the inference speed. More explanation may be referred to the paper "LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale". 

If you really find some bugs in our code, please let us know.
