### ISSUE TITLE
The training environment

### ISSUE THREAD

**Issue by BeachWang** [MILVLG/imp#6]
Hi,

I try to reproduction the training of Imp. But there is some problem with the training environment as following shows.

<img width="1024" alt="截屏2024-02-12 上午8 41 47" src="https://github.com/MILVLG/imp/assets/22676348/1c5a0a99-b407-4708-9f4b-414b2a8e10df">

My transformers is 4.31.0 as requirement.

**Comment by ParadoxZW** [comment]
Hi! Thanks for your interesting and response!

It seems that [phi-2](https://huggingface.co/microsoft/phi-2) has changed their `config.json` structure. There are some argument names are different with those in the version when I cloned the repository.

I will update the code and make it compatible for the new `config.json` as soon as possible!

For a walkaround, you can replace the content in the `config.json` with the following
```JSON
{
  "_name_or_path": "microsoft/phi-2",
  "activation_function": "gelu_new",
  "architectures": [
    "PhiForCausalLM"
  ],
  "attn_pdrop": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_phi.PhiConfig",
    "AutoModelForCausalLM": "modeling_phi.PhiForCausalLM"
  },
  "embd_pdrop": 0.0,
  "flash_attn": false,
  "flash_rotary": false,
  "fused_dense": false,
  "img_processor": null,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "phi-msft",
  "n_embd": 2560,
  "n_head": 32,
  "n_head_kv": null,
  "n_inner": null,
  "n_layer": 32,
  "n_positions": 2048,
  "resid_pdrop": 0.1,
  "rotary_dim": 32,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.35.2",
  "vocab_size": 51200
}
```

**Comment by ParadoxZW** [comment]
Hi @BeachWang 
The code has been updated. Feel free to feedback if you meet other errors after this one :)

**Comment by BeachWang** [comment]
By the way, it should be `deepspeed imp_llava/train/train_mem.py` in `pretrain.sh` but not `deepspeed llava/train/train_mem.py` similar with the typo in `finetune.sh`.

**Comment by ParadoxZW** [comment]
Yes, you are right :)
