### ISSUE TITLE
Model Evaluation

### ISSUE THREAD

**Issue by BeachWang** [MILVLG/imp#8]
Hi,

I have trained imp with lora. However, it does not process the reference when I run the evaluation scripts.
Following is the output when I eval pope.
<img width="1354" alt="截屏2024-02-17 下午12 17 51" src="https://github.com/MILVLG/imp/assets/22676348/59ec0f05-53a2-4dbc-8331-e682fff839fd">

**Comment by bruceisme** [comment]
Hi, thanks for your interest.  You can add `--model-base microsoft/phi-2  \` to the following code in `pope.sh`. Then it might work and start to run the scripts.
https://github.com/MILVLG/imp/blob/48bdc607089385e017f7b5c1f16762625a39eaf1/scripts/eval/pope.sh#L22-L29
And we will fix this problem as soon as possible. Let me know if there's any other questions.

**Comment by BeachWang** [comment]
Hi @ParadoxZW . Do we need to roll back the code for #7 if we use the old version of phi-2, since the codes for training have been made compatible to the new version of phi-2.

**Comment by BeachWang** [comment]
Hi,
I have succeed in reproducing your work. But I find there are some problems in the eval of pope and sqa. Specifically, it should be `$EVAL_CKPT` but not `$CKPT` in line 27 and 47 in `pope.sh`. As for sqa, I got the following error when running `sqa.sh`.
<img width="875" alt="截屏2024-02-26 下午2 33 44" src="https://github.com/MILVLG/imp/assets/22676348/891f0cde-db28-48b6-acc8-459a4f5e4e80">
The reason seems be that imp use `model_vqa_loader` to eval sqa, but LLaVA use `model_vqa_science` actually.
